name = "spicy"
version = "0.1.0"
description = "A statically typed systems programming language with both compilation and interpretation capabilities, featuring a Lisp-inspired syntax."

licences = ["MIT"]


target = "javascript"

[dependencies]
gleam_stdlib = "~> 0.30"
simplifile = "~> 0.1.14"


[dev-dependencies]
gleeunit = "~> 0.10"


[javascript]
runtime = "deno"

[javascript.deno]
allow_all = true
