name: test

on:
  push:
    branches: ['main']

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: denoland/setup-deno@v1.1.2
      - uses: erlef/setup-beam@v1
        with:
          deno-version: v1.x
          otp-version: false
          gleam-version: "0.30.5"
      - run: gleam format --check src test
      - run: gleam deps download
      - run: gleam test
